services:
  - type: web
    name: lotplan-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    plan: free
    autoDeploy: true
    envVars:
      - key: VITE_API_BASE
        value: https://lotplan-backend.onrender.com
    
  - type: web
    name: lotplan-backend
    env: docker
    rootDirectory: backend
    plan: free
    autoDeploy: true
    envVars:
      - key: CORS_ORIGINS
        value: https://lotplan-frontend.onrender.com
      - key: HTTP_TIMEOUT_SECONDS
        value: "60"
      - key: ARCGIS_CONCURRENCY
        value: "4"
