schemaVersion: 1
services:
  # --- Frontend as a Node Web Service (build + serve dist) ---
  - type: web
    name: lotplan-frontend
    runtime: node          # use 'runtime' per current spec
    rootDirectory: .
    plan: free
    autoDeploy: true
    # Build: write .env.production using backend's external hostname, then build
    buildCommand: VITE_API_BASE=https://${BACKEND_HOST} npm ci && npm run build
    # Serve the static build
    startCommand: npm run start
    envVars:
      # Pull the backend's external hostname into BACKEND_HOST
      - key: BACKEND_HOST
        fromService:
          type: web
          name: lotplan-backend
          envVarKey: RENDER_EXTERNAL_HOSTNAME
      # (optional) pin Node version if you like
      # - key: RENDER_NODE_VERSION
      #   value: 20

  # --- Backend (Docker) ---
  - type: web
    name: lotplan-backend
    runtime: docker
    rootDirectory: backend
    plan: free
    autoDeploy: true
    envVars:
      - key: CORS_ORIGINS
        value: http://localhost:5173,https://lotplan-frontend.onrender.com
      - key: HTTP_TIMEOUT_SECONDS
        value: "60"
      - key: ARCGIS_CONCURRENCY
        value: "4"