schemaVersion: 1
services:
  - type: static_site 
    name: lotplan-frontend
    rootDirectory: .
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_BASE
        fromService:
          type: web
          name: lotplan-backend
          property: url

  - type: web
    name: lotplan-backend
    env: docker
    rootDirectory: backend
    plan: free
    autoDeploy: true
    envVars:
      - key: CORS_ORIGINS
        value: http://localhost:5173,https://lotplan-frontend.onrender.com
      - key: HTTP_TIMEOUT_SECONDS
        value: "60"
      - key: ARCGIS_CONCURRENCY
        value: "4"
