services:
  - type: web
    name: lotplan-backend
    env: docker
    rootDirectory: backend
    plan: free
    autoDeploy: true
    envVars:
      - key: CORS_ORIGINS
        value: http://localhost:5173
      - key: HTTP_TIMEOUT_SECONDS
        value: "60"
      - key: ARCGIS_CONCURRENCY
        value: "4"
